config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :settings, only: [:index, :create, :update]
  resources :parts
  resources :models
  resources :products
  resources :image_layers, only: [:new, :create, :show, :update, :destroy]
  resources :avitos, only: [:index]

  resources :stores do
    post '/update_img', to: 'jobs#update_img'
    post '/update_feed', to: 'jobs#update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list', as: 'update_ban_list'

    resources :streets, only: [:index, :create, :update, :destroy]
    resources :maps, only: [:show]
    resources :addresses, only: [:new, :create, :show, :update, :destroy]

    namespace :avito do
      get '/dashboard', to: 'dashboard#index'
      get '/reports', to: 'reports#index'
      get '/reports/:id', to: 'reports#show'
      get '/items', to: 'items#index'
      get '/autoload/edit', to: 'autoload#edit'
      patch '/autoload', to: 'autoload#update'
      get '/autoload', to: 'autoload#show'
      post '/autoload/update_ads', to: 'autoload#update_ads'
    end

    match '/avito', to: 'avito/dashboard#index', via: :get
  end

  post '/update_products_img', to: 'jobs#update_products_img', as: 'update_products_img'

  root 'google_sheets#index'
  get '/google_sheets', to: 'google_sheets#index'

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => "/exception-track"
  end
end

app/models/store.rb
class Store < ApplicationRecord
  validates :var, presence: true, uniqueness: true
  validates :category, presence: true
  validates :goods_type, presence: true
  validates :ad_type, presence: true
  validates :type, presence: true
  validates :description, presence: true
  validates :condition, presence: true
  validates :allow_email, presence: true
  validates :manager_name, presence: true
  validates :contact_phone, presence: true, uniqueness: { case_sensitive: false }

  has_many :image_layers, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :avito_tokens, dependent: :destroy
  has_many :ban_lists, dependent: :destroy
  has_many :ads, dependent: :destroy

  belongs_to :user

  before_save :set_default_layer_params, :cleanup_description

  self.inheritance_column = :type_

  private

  def set_default_layer_params
    game_img_params.present? || self.game_img_params = nil
  end

  def cleanup_description
    if description.present?
      description.squeeze!(' ')
      description.strip!
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Stores', '/stores'
  before_action :set_breadcrumbs, only: [:show, :edit]

  def index
    @stores = current_user.stores.order(active: :desc).order(:created_at)
  end

  def show
    @pagy, @ads = pagy(@store.ads.order(created_at: :desc), items: 50)
    @whitelist  = { elements: %w[div span ul li br b i strong em p] }
  end

  def new
    @store = current_user.stores.build
  end

  def create
    @store = current_user.stores.build(store_params)

    if @store.save
      msg = ["Магазин #{@store.manager_name} был успешно добавлен."]
      msg << 'Внимание магазин не активен!' if store_params[:active].to_i.zero?
      flash[:success] = msg
      redirect_to @store
    else
      error_notice(@store.errors.full_messages)
    end
  end

  def edit; end

  def update
    if @store.update(store_params)
      msg = ["Магазин #{@store.manager_name} был успешно обновлен."]
      msg << 'Внимание магазин не активен!' if store_params[:active].to_i.zero?
      flash[:success] = msg
      redirect_to @store
    else
      error_notice(@store.errors.full_messages)
    end
  end

  def destroy
    if @store.destroy
      msg = "Магазин #{@store.manager_name} был успешно удален."
      render turbo_stream: [ turbo_stream.remove("store_#{@store.id}"), success_notice(msg)]
    else
      error_notice(@store.errors.full_messages)
    end
  end

  private

  def set_store
    @store = current_user.stores.find(params[:id])
  end

  def set_breadcrumbs
    add_breadcrumb @store.manager_name, store_path(@store)
  end

  def store_params
    params.require(:store)
          .permit(:manager_name, :var, :ad_status, :category, :goods_type, :ad_type, :type, :desc_game,
                  :menuindex, :active, :contact_method, :description, :condition, :desc_product, :percent,
                  :allow_email, :contact_phone, :game_img_params, :table_id, :client_id, :client_secret)
  end
end

app/views/stores/_ads.html.erb
<div class="tab-pane fade" id="ads" role="tabpanel" aria-labelledby="ads-tab">
  <%= turbo_frame_tag :ads do %>
    <% if @ads.present? %>
      <ul class="list-group" data-controller="fancybox">
        <li class="list-group-item list-group-item-action active d-none d-md-block">
          <div class="row">
            <div class="col-1">№</div>
            <div class="col-1">Img</div>
            <div class="col-4">Title</div>
            <div class="col-2">File id</div>
            <div class="col-1">Deleted</div>
            <div class="col-1">Baned</div>
            <div class="col-2">Заблокировано до</div>
          </div>
        </li>
        <% @ads.each do |item| %>
          <li class="list-group-item list-group-item-action">
            <div class="row">
              <div class="col-6 col-md-1"><%= item.id %></div>
              <div class="col-6 col-md-1">
                <% if item.image.attached? %>
                  <a data-fancybox="gallery" data-src="<%= url_for(item.image) %>" data-caption="<%= item.title %>">
                    <div class="loading-image" style='width: 50px; height: 50px'>
                      <div class="photo-thumbnail" style="background-image: url(<%= url_for(item.image) %>);"></div>
                    </div>
                  </a>
                <% end %>
              </div>
              <div class="col-12 col-md-4"><%= item.title %></div>
              <div class="col-6 col-md-2"><%= item.file_id %></div>
              <div class="col-6 col-md-1"><%= item.deleted %></div>
              <div class="col-6 col-md-1"><%= item.banned %></div>
              <div class="col-6 col-md-2"><%= item.banned_until %></div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>Записей не найдено!</p>
    <% end %>

    <div data-controller="pagy-initializer" class="mt-3 mb-3">
      <%== pagy_bootstrap_nav_js(@pagy) if @pagy.pages > 1 %>
    </div>

    <%== pagy_info(@pagy) %>
  <% end %>
</div>

app/views/stores/_ban_list.html.erb
<div class="tab-pane fade" id="ban" role="tabpanel" aria-labelledby="ban-tab">
  <%= turbo_frame_tag :ban do %>
    <% if @ban.present? %>
      <ul class="list-group">
        <li class="list-group-item list-group-item-action active d-none d-md-block">
          <div class="row">
            <div class="col-1">№</div>
            <div class="col-2">№ отчета</div>
            <div class="col-5">Avito ID</div>
            <div class="col-2">Добавлено</div>
            <div class="col-2">Заблокировано до</div>
          </div>
        </li>
        <% @ban.each do |item| %>
          <li class="list-group-item list-group-item-action">
            <div class="row">
              <div class="col-6 col-md-1"><%= item.id %></div>
              <div class="col-6 col-md-2"><%= item.report_id %></div>
              <div class="col-12 col-md-5"><%= item.ad_id %></div>
              <div class="col-6 col-md-2"><%= format_date item.created_at %></div>
              <div class="col-6 col-md-2"><%= format_date item.expires_at %></div>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div data-controller="pagy-initializer" class="mt-3 mb-3">
      <%== pagy_bootstrap_nav_js(@pagy) if @pagy.pages > 1 %>
    </div>

    <%== pagy_info(@pagy) %>
  <% end %>
</div>

app/views/stores/_form.html.erb
<%= form_with(model: @store, url: url, method: method) do |form| %>
  <div class="mb-3">
    <%= form.label :manager_name, class: 'form-label' %>
    <%= form.text_field :manager_name, class: 'form-control', placeholder: 'Manager name' %>
  </div>

  <div class="mb-3">
    <%= form.label :var, class: 'form-label' %>
    <%= form.text_field :var, class: 'form-control', placeholder: 'var' %>
  </div>

  <div class="mb-3">
    <%= form.label :ad_status, class: 'form-label' %>
    <%= form.text_field :ad_status, class: 'form-control', placeholder: 'Ad status' %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class: 'form-label' %>
    <%= form.text_field :category, value: @store.category || 'Игры, приставки и программы',
                        class: 'form-control', placeholder: 'Category' %>
  </div>

  <div class="mb-3">
    <%= form.label :goods_type, class: 'form-label' %>
    <%= form.text_field :goods_type, value: @store.goods_type || 'Игры для приставок',
                        class: 'form-control', placeholder: 'Игры для приставок' %>
  </div>

  <div class="mb-3">
    <%= form.label :ad_type, class: 'form-label' %>
    <%= form.text_field :ad_type, value: @store.ad_type || 'Товар приобретен на продажу',
                        class: 'form-control', placeholder: 'Товар приобретен на продажу' %>
  </div>

  <div class="mb-3">
    <%= form.label :type, class: 'form-label' %>
    <%= form.text_field :type, value: @store.type || 'Другое', class: 'form-control', placeholder: 'Другое' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, 'Общее описание', class: 'form-label' %>
    <%= form.rich_text_area :description, size: '50x7', class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="mb-3">
    <label for="desc_game" class="form-label">Описание для Игр</label>
    <%= form.rich_text_area :desc_game, size: '50x5', class: 'form-control', placeholder: 'Описание для Игр' %>
  </div>

  <div class="mb-3">
    <label for="desc_product" class="form-label">Описание для других объявлений</label>
    <%= form.rich_text_area :desc_product, size: '50x5',
                            class: 'form-control', placeholder: 'Описание для других объявлений' %>
  </div>

  <div class="mb-3">
    <label for="condition" class="form-label">Condition</label>
    <%= form.text_field :condition, value: @store.condition || 'Новое', class: 'form-control', placeholder: 'Новое' %>
  </div>

  <div class="mb-3">
    <label for="allow_email" class="form-label">Allow email</label>
    <%= form.text_field :allow_email, value: @store.allow_email || 'Нет', class: 'form-control', placeholder: 'Нет' %>
  </div>

  <div class="mb-3">
    <%= form.label :contact_phone, class: 'form-label' %>
    <%= form.text_field :contact_phone, class: 'form-control', placeholder: 'Телефон' %>
  </div>

  <div class="mb-3">
    <label for="contact_method" class="form-label">Способ связи</label>
    <%= form.select :contact_method, options_for_select(['По телефону и в сообщениях', 'По телефону', 'В сообщениях'],
                                                        @store.contact_method), {}, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="game_img_params" class="form-label">Параметры картинки игры</label>
    <%= form.text_field :game_img_params, class: 'form-control',
                       placeholder: "Нужно указать ввиде json: { pos_x: 448, pos_y: 208, row: 1024, column: 1024 }" %>
  </div>

  <div class="mb-3">
    <%= form.label :menuindex, 'Расположение картинки в слоях изображения для авито', class: 'form-label' %>
    <%= form.number_field :menuindex, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :client_id, class: 'form-label' %>
    <%= form.text_field :client_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :client_secret, class: 'form-label' %>
    <%= form.text_field :client_secret, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :percent, class: 'form-label' %>
    <%= form.number_field :percent, class: 'form-control', min: -100, max: 100 %>
  </div>

  <div class="mb-3">
    <%= form.check_box :active, { checked: @store.active, class: 'form-check-input' } %>
    <%= form.label :active, class: 'form-check-label' %>
  </div>

  <div class="mb-3">
    <%= form.submit (method == :patch ? 'Save' : 'Add'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<li class="list-group-item list-group-item-action<%= ' list-group-item-danger' unless store.active %>" id="store_<%= store.id %>">
  <div class="row">
    <div class="col-5 col-md-9">
      <%= link_to store.manager_name, store_path(store.id) %>
    </div>

    <div class="col-1 d-flex justify-content-end align-items-center">
      <% if store.active %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggle-on" viewBox="0 0 16 16">
          <path d="M5 3a5 5 0 0 0 0 10h6a5 5 0 0 0 0-10zm6 9a4 4 0 1 1 0-8 4 4 0 0 1 0 8"/>
        </svg>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggle-off" viewBox="0 0 16 16">
          <path d="M11 4a4 4 0 0 1 0 8H8a5 5 0 0 0 2-4 5 5 0 0 0-2-4zm-6 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8M0 8a5 5 0 0 0 5 5h6a5 5 0 0 0 0-10H5a5 5 0 0 0-5 5"/>
        </svg>
      <% end %>
    </div>

    <div class="col-6 col-md-2 d-flex justify-content-end gap-1">
      <%= link_to 'Edit', edit_store_path(store.id), class: "btn btn-warning", style: 'max-height: 39px;' %>

      <div style="display: inline-block;">
        <%= button_to "Delete", store_path(store.id),
                      method: :delete, class: 'btn btn-danger',
                      data: { confirm: 'Are you sure you want to delete this store?',
                              controller: 'confirm', action: 'click->confirm#call' } %>
      </div>
    </div>
  </div>
</li>

app/views/stores/edit.html.erb
<% content_for :title do %>
  Редактирование магазина <%= @store.manager_name %>
<% end %>

<%= turbo_frame_tag @store do %>
  <div class="container">
    <%= render partial: '/stores/form', locals: { url: store_path(@store), method: :patch } %>
  </div>
<% end %>

app/views/stores/index.html.erb
<div class="container">
  <h1>Магазины:</h1>
  <a href="<%= new_store_path %>" class="btn btn-success mb-3">Add</a>
  <ol class="list-group list-group-numbered">
    <%= render @stores %>
  </ol>
</div>

app/views/stores/new.html.erb
<% content_for :title do %>
  Создать новый магазин
<% end %>

<div class="container">
  <%= render partial: '/stores/form', locals: { url: stores_path, method: :past } %>
</div>

app/views/stores/show.html.erb
<% content_for :title do %>
  Магазин <%= @store.manager_name %>
  <% if !@store.percent.zero? %>
    <span class="percent"><%= '+' if @store.percent.positive?  %><%= "#{@store.percent}" %>%</span>
  <% end %>
<% end %>

<% content_for :head do %>
  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=369d354e-0df0-4d9d-bb3a-08bc6a532a15" type="text/javascript"></script>
<% end %>

<%= turbo_frame_tag @store do %>
  <div class="container">
    <div class="d-flex gap-3">
      <%= button_to 'Обновить feed', store_update_feed_path(@store),
                    class: 'loader-btn btn btn-success btn-upd-feed',
                    data: { controller: 'btn_preloader', action: 'click->btn_preloader#call' } %>

      <%= button_to 'Обновить Black list', store_update_ban_list_path(@store),
                    class: 'loader-btn btn btn-dark' %>
    </div>

    <ul class="nav nav-tabs mt-2 mt-md-3" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Основная информация</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="address-tab" data-bs-toggle="tab" data-bs-target="#address" type="button" role="tab" aria-controls="address" aria-selected="false">Адреса магазина</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Слои картинки</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="bans-tab" data-bs-toggle="tab" data-bs-target="#ads" type="button" role="tab" aria-controls="ads" aria-selected="false">Объявления</button>
      </li>
    </ul>

    <div class="tab-content mt-3" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <a href="<%= edit_store_path(@store.id) %>" class='mb-3 btn btn-warning'>Edite</a>

        <ul class="list-group">
          <% @store.attributes.keys.reject { |i| i.match?(/^id|created_at|updated_at/) }.each do |name| %>
            <li class="list-group-item list-group-item-action overflow-hidden">
              <strong><%= name %>: </strong>
              <%= name.match?(/description|desc_game|desc_product/) ? Sanitize.fragment(@store.send(name.to_sym), @whitelist).html_safe : @store.send(name.to_sym) %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane fade show" id="address" role="tabpanel" aria-labelledby="address-tab">
        <%= render partial: '/addresses/new_address_btn', locals: { store: @store } %>

        <ul class="list-group" id="addresses">
          <%= render @store.addresses.order(:id) %>
        </ul>
      </div>

      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <%= render partial: '/image_layers/new_image_layer_btn', locals: { store: @store } %>

        <ol class="list-group list-group-numbered" id="image_layers">
          <%= render @store.image_layers.order(:menuindex, :id) %>
        </ol>
      </div>

      <%= render '/stores/ads' %>
    </div>
  </div>
<% end %>