config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :settings, only: [:index, :create, :update]
  resources :parts
  resources :models
  resources :products
  resources :image_layers, only: [:new, :create, :show, :update, :destroy]
  resources :avitos, only: [:index]

  resources :stores do
    post '/update_img', to: 'jobs#update_img'
    post '/update_feed', to: 'jobs#update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list', as: 'update_ban_list'

    resources :streets, only: [:index, :create, :update, :destroy]
    resources :maps, only: [:show]
    resources :addresses, only: [:new, :create, :show, :update, :destroy]

    namespace :avito do
      get '/dashboard', to: 'dashboard#index'
      get '/reports', to: 'reports#index'
      get '/reports/:id', to: 'reports#show'
      get '/items', to: 'items#index'
      get '/autoload/edit', to: 'autoload#edit'
      patch '/autoload', to: 'autoload#update'
      get '/autoload', to: 'autoload#show'
      post '/autoload/update_ads', to: 'autoload#update_ads'
    end

    match '/avito', to: 'avito/dashboard#index', via: :get
  end

  post '/update_products_img', to: 'jobs#update_products_img', as: 'update_products_img'

  root 'google_sheets#index'
  get '/google_sheets', to: 'google_sheets#index'

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => "/exception-track"
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:show]

  def show
    if @address
      render turbo_stream: [
        turbo_stream.replace("address_#{@address.id}", partial: '/maps/map', locals: { address: @address }),
      ]
    else
      error_notice(@address&.errors&.full_messages || 'Error getting address')
    end
  end


  private

  def set_address
    store    = current_user.stores.find(params[:store_id])
    @address = store.addresses.find(params[:address_id]) if store
  end
end

app/views/maps/_map.html.erb
<li class="list-group-item list-group-item-action" id="address_<%= address.id %>">
  <div class="row mb-2">
    <div class="col-11">
      <h5>Покрытие <%= address.city %>:</h5>
    </div>
    <div class="col-1">
      <div class="d-flex justify-content-end">
        <%= link_to store_address_path(id: address, store_id: address.store), title: 'Назад', class: 'btn btn-primary btn-sm',
                    data: { turbo_prefetch: false } do %>
          <i class="bi bi-backspace"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div data-controller="map">
    <div data-map-target="addresses" style="display: none">
      <% address.streets.each do |street| %>
        <span><%= "#{address.city}, #{street.title}" %></span>
      <% end %>
    </div>
    <div id="map" class="mb-3" data-map-target="map"></div>
  </div>
</li>