config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :settings, only: [:index, :create, :update]
  resources :parts
  resources :models
  resources :products
  resources :image_layers, only: [:new, :create, :show, :update, :destroy]
  resources :avitos, only: [:index]

  resources :stores do
    post '/update_img', to: 'jobs#update_img'
    post '/update_feed', to: 'jobs#update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list', as: 'update_ban_list'

    resources :streets, only: [:index, :create, :update, :destroy]
    resources :maps, only: [:show]
    resources :addresses, only: [:new, :create, :show, :update, :destroy]

    namespace :avito do
      get '/dashboard', to: 'dashboard#index'
      get '/reports', to: 'reports#index'
      get '/reports/:id', to: 'reports#show'
      get '/items', to: 'items#index'
      get '/autoload/edit', to: 'autoload#edit'
      patch '/autoload', to: 'autoload#update'
      get '/autoload', to: 'autoload#show'
      post '/autoload/update_ads', to: 'autoload#update_ads'
    end

    match '/avito', to: 'avito/dashboard#index', via: :get
  end

  post '/update_products_img', to: 'jobs#update_products_img', as: 'update_products_img'

  root 'google_sheets#index'
  get '/google_sheets', to: 'google_sheets#index'

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => "/exception-track"
  end
end

app/controllers/avito/autoload_controller.rb
module Avito
  class AutoloadController < ApplicationController
    include AvitoConcerns
    before_action :ensure_turbo_stream_request, only: [:edit, :show]
    before_action :set_auto_load, only: [:show, :edit]
    layout 'avito'

    def show
      @report = fetch_and_parse 'https://api.avito.ru/autoload/v2/reports/last_completed_report'
      @tz     = TZInfo::Timezone.get(Rails.application.config.time_zone)
    end

    def edit
      render turbo_stream: [turbo_stream.replace(@store, partial: '/avito/autoload/edit')]
    end

    def update
      weekdays         = params[:store][:weekdays].reject(&:blank?).map { |i| i.to_i }
      time_slots       = params[:store][:time_slots].reject(&:blank?).map { |i| i.to_i }
      autoload_enabled = params[:store][:autoload_enabled] == '1'
      avito_json       = { agreement: true,
                           autoload_enabled: autoload_enabled,
                           schedule: [{ rate: params[:store][:rate].to_i, time_slots: time_slots, weekdays: weekdays }]
      }
      keys_to_include = %i[upload_url report_email]
      avito_json.merge! autoload_params.slice(*keys_to_include)
      result = @avito.connect_to('https://api.avito.ru/autoload/v1/profile', :post, avito_json)

      if result&.status == 200
        set_auto_load
        Rails.cache.delete("auto_load_#{@store.id}")
        msg = t 'avito.notice.upd_autoload_conf'
        render turbo_stream: [turbo_stream.replace(@store, partial: '/avito/autoload/show'), success_notice(msg)]
      else
        error_notice t('avito.error.upd_autoload_conf')
      end
    end

    def update_ads
      result = @avito.connect_to('https://api.avito.ru/autoload/v1/upload', :post)
      if result&.status == 200
        render turbo_stream: success_notice(t 'avito.notice.upd_ads')
      else
        error_notice(t 'avito.error.upd_ads')
      end
    end

    private

    def ensure_turbo_stream_request
      redirect_to store_avito_dashboard_path unless turbo_frame_request?
    end

    def set_auto_load
      @auto_load = fetch_and_parse 'https://api.avito.ru/autoload/v1/profile'
    end

    def autoload_params
      params.require(:store).permit(:upload_url, :report_email, :autoload_enabled, :rate, weekdays: [], time_slots: [])
    end
  end
end

app/controllers/avito/dashboard_controller.rb
module Avito
  class DashboardController < ApplicationController
    include AvitoConcerns
    add_breadcrumb "Dashboard", :store_avito_dashboard_path
    layout 'avito'

    def index
      @account   = fetch_cached("account_#{@store.id}", 'https://api.avito.ru/core/v1/accounts/self')
      @auto_load = fetch_cached("auto_load_#{@store.id}", 'https://api.avito.ru/autoload/v1/profile')
      @report    = fetch_cached("report_#{@store.id}",
                                'https://api.avito.ru/autoload/v2/reports/last_completed_report')
      @bal       = fetch_cached( "bal_#{@store.id}", 'https://api.avito.ru/cpa/v2/balanceInfo', :post, {})
      @balance   = fetch_cached("balance_#{@store.id}", "https://api.avito.ru/core/v1/accounts/#{@account['id']}/balance/")
      @rate      = fetch_cached("rate_#{@store.id}", 'https://api.avito.ru/ratings/v1/info')
    rescue => e
       Rails.logger.error e.message
       error_notice e
    end

    private

    def fetch_cached(cache_key, url, method=:get, payload=nil)
      Rails.cache.fetch(cache_key, expires_in: 5.minutes) { fetch_and_parse(url, method, payload) }
    end
  end
end

app/controllers/avito/items_controller.rb
module Avito
  class ItemsController < ApplicationController
    include AvitoConcerns
    layout 'avito'

    def index
      add_breadcrumb @store.manager_name, store_avito_dashboard_path
      add_breadcrumb 'Items', store_avito_items_path
      page     = params['page'].to_i.zero? ? 1 : params['page'].to_i
      per_page = params['per_page'] || 100
      url      = "https://api.avito.ru/core/v1/items?page=#{page}&per_page=#{per_page}"
      @items   = fetch_and_parse url

      session["store_#{@store.id}_size"] ||= @items['resources'].size if page == 1
      @size = session["store_#{@store.id}_size"] || per_page
      if @items['resources'].size == per_page && page >= (session["store_#{@store.id}_end_page"] ||= 1)
        session["store_#{@store.id}_end_page"] = page + 1
      end
      @end_page = session["store_#{@store.id}_end_page"] || 1
    end
  end
end

app/controllers/avito/reports_controller.rb
module Avito
  class ReportsController < ApplicationController
    include AvitoConcerns
    before_action :set_breadcrumb, only: [:index, :show]
    before_action :handle_sections_params, only: [:show]
    layout 'avito'

    def index
      @reports = fetch_and_parse "https://api.avito.ru/autoload/v2/reports?page=#{params['page'].to_i}"
    end

    def show
      avito_url = "https://api.avito.ru/autoload/v2/reports/#{params['id']}"
      unless turbo_frame_request?
        initialize_cache
        @cached   = @cached_report.report.present?
        @report   = set_cache(avito_url, :report)
        money_url = "#{avito_url}/items/fees"
        @money    = set_cache(money_url, :fees)

        add_breadcrumb @report['report_id']
      end

      @items = fetch_and_parse "#{avito_url}/items?sections=#{params['sections']}&page=#{params['page'].to_i}"

      if turbo_frame_request?
        return render turbo_stream: turbo_stream.update(:reports, partial: '/avito/reports/item_page')
      end
    end

    private

    def set_cache(url, section)
      result = @cached_report&.send(section)
      return result if result

      result         = fetch_and_parse(url)
      will_pub_later = section == :fees ||
        !result['section_stats']['sections']&.find { |i| i['slug'] == 'will_publish_later' }
      if params['no_cache'].nil? && result['status'] != 'processing' && will_pub_later
        @cached_report.public_send("#{section}=", result)
        @cached_report.save
      end
      result
    end

    def initialize_cache
      @cached_report =
        if params['no_cache'].nil?
          CacheReport.find_or_initialize_by(report_id: params['id'], store_id: @store.id)
        else
          CacheReport.where(report_id: params['id'], store_id: @store.id).delete_all
          CacheReport.new(report_id: params['id'], store_id: @store.id)
        end
    end

    def handle_sections_params
      if params['sections'].to_s == 'nil'
        session[:sections] = params['sections'] = nil
      else
        session[:sections] = params['sections'] if params['sections'].present?
        params['sections'] ||= session[:sections]
      end
    end

    def set_breadcrumb
      add_breadcrumb @store.manager_name, store_avito_dashboard_path(@store)
      add_breadcrumb "Reports", :store_avito_reports_path
    end
  end
end

app/controllers/avitos_controller.rb
class AvitosController < ApplicationController
  before_action :authenticate_user!

  def index
    @stores = current_user.stores.order(:created_at)
  end
end

app/helpers/avito/autoload_helper.rb
module Avito
  module AutoloadHelper
    TIME_SLOTS = [*0..23].map { |i| { id: i, name: "#{i}:00-#{i+1}:00" } }.freeze
  end
end

app/helpers/avito/dashboard_helper.rb
module Avito
  module DashboardHelper
    WEEKDAYS = [
      { id: 0, name: 'Понедельник' },
      { id: 1, name: 'Вторник' },
      { id: 2, name: 'Среда' },
      { id: 3, name: 'Четверг' },
      { id: 4, name: 'Пятница' },
      { id: 5, name: 'Суббота' },
      { id: 6, name: 'Воскресенье' }
    ].freeze
  end
end

app/helpers/avito/reports_helper.rb
module Avito
  module ReportsHelper
    def badge_style(slug)
      if slug == 'error_rejected'
        'bg-warning text-dark'
      elsif slug.match?(/error_deleted|removed_complete/)
        'bg-danger'
      elsif slug == 'error_blocked'
        'bg-dark'
      elsif slug == 'success_added'
        'bg-success'
      elsif slug == 'success_activated_updated'
        'bg-info text-dark'
      elsif slug == 'success_skipped'
        'bg-light text-dark'
      elsif slug == 'stopped_by_expiration'
        'bg-secondary'
      else
        'bg-primary'
      end
    end

    def badge_status(status)
      case status
      when /warning/
        'warning text-dark'
      when /success/
        'success'
      when /error/
        'danger'
      else
        'primary'
      end
    end

    def safe_html(html)
      whitelist = {
        elements: %w[div span ul li br b i strong em p a],
        attributes: { 'a' => %w[href title] }
      }
      Sanitize.fragment(html, whitelist).html_safe
    end
  end
end

app/views/avito/dashboard/index.html.erb
<% content_for :title do %>
  Управление avito аккаунтом <%= @store.manager_name %>
<% end %>

<div class="container">
  <h3 class="mt-3 mb-3">Информация об аккаунте</h3>

  <ul class="list-group">
    <% @account.each do |key, val| %>
      <% next if key == 'profile_url' %>

      <li class="list-group-item list-group-item-action">
        <div class="row" style="overflow: hidden;">
          <div class="fw-bold col-6 col-md-3">
            <%= t("avito.autoload.#{key}") %>:
          </div>
          <div class="col-6 col-md-9">
            <% if key == 'name' %>
              <%= link_to val, @account['profile_url'], target: '_blank' %>
            <% else %>
              <%= val %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
    <li class="list-group-item list-group-item-action">
      <div class="row">
        <div class="fw-bold col-6 col-md-3">Рейтинг</div>
        <div class="col-6 col-md-9">
          <span style="font-size: 1.2em; margin-right: 10px"><%= "#{@rate['rating']['score']}" %></span>
          <%= "Голосов: #{@rate['rating']['reviewsWithScoreCount']}" %>
          <%= "Коментариев: #{@rate['rating']['reviewsCount']}" %>
        </div>
      </div>
    </li>
    <li class="list-group-item list-group-item-action">
      <div class="row">
        <div class="fw-bold col-6 col-md-3">Кошелёк</div>
        <div class="col-6 col-md-9">
          <%= "Баланс: #{@balance['real']}" %>
          <%= "Бонусы: #{@balance['bonus']}" %>
        </div>
      </div>
    </li>

    <li class="list-group-item list-group-item-action">
      <div class="row">
        <div class="fw-bold col-6 col-md-3">Баланс тарифа</div>
        <div class="col-6 col-md-9">
          <% balance = @bal['result']['balance'] / 100 %>
          <span style="font-size: 1.2em; <%= balance < 100 ? 'color: red; ' : '' %>margin-right: 10px;">
            <%= "#{balance}₽" %>
          </span>

          <% if @bal['result']['debt'] > 0 %>
            <span style="color: red; margin-right: 10px;"><%= "Долг: #{@bal['result']['debt'] / 100 }₽" %></span>
          <% end %>

          <span>
            Aванс текущего месяца: <span style="font-size: 1.1em;"><%= "#{@bal['result']['advance'] / 100}₽" %></span>
          </span>
        </div>
      </div>
    </li>
  </ul>

  <h3 class="mt-3 mb-3">Информация об автозагрузке</h3>

  <%= turbo_frame_tag @store do %>
    <ul class="list-group">
      <% @auto_load.each do |key, val| %>
        <li class="list-group-item list-group-item-action">
          <div class="row" style="overflow: hidden;">
            <% if val.is_a?(Array) %>
              <div class="col-6 col-md-3">
                <h5><%= t("avito.autoload.#{key}") %>:</h5>
              </div>
            <% else %>
              <div class="fw-bold col-6 col-md-3">
                <%= t("avito.autoload.#{key}") %>:
              </div>
              <div class="col-6 col-md-9">
                <% if key == 'autoload_enabled' %>
                  <%= val == true ? 'Включено' : 'Отключено' %>
                <% elsif key == 'upload_url' %>
                  <%= link_to val, val, title: t("avito.autoload.#{key}") %>
                <% else %>
                  <%= val %>
                <% end %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>

      <% @auto_load['schedule'].first&.each do |k, v| %>
        <li class="list-group-item list-group-item-action">
          <div class="row">
            <div class="fw-bold col-6 col-md-3">
              <%= t("avito.autoload.#{k}") %>:
            </div>
            <div class="col-6 col-md-9">
              <% if k == 'weekdays' %>
                <%= v.map { |i| Avito::DashboardHelper::WEEKDAYS[i][:name] }.join(', ') %>
              <% elsif v.is_a?(Array) %>
                <%= v.sort.map { |i| "#{i}.00-#{i+1}.00" }.join(', ') %>
              <% else %>
                <%= v %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>

    <%= link_to 'Edit', store_avito_autoload_edit_path, data: { turbo_prefetch: false }, class: 'mt-3 btn btn-warning' %>
  <% end %>

  <div class="avito-buttons">
    <%= button_to 'Update', store_avito_autoload_update_ads_path, class: 'mt-3 btn btn-success',
                  data: { confirm: 'Вы уверены, что хотите обновить объявления? Их можно обновлять не чаще одного раза в час.',
                          controller: 'confirm', action: 'click->confirm#call', turbo_prefetch: 'false' } %>
  </div>

  <h3 class="mt-3 mb-3">Отчет по последней загрузке</h3>

  <ul class="list-group">
    <% @report.to_a[0..4].to_h.each do |key, val| %>
      <% next if key == 'finished_at' || val.is_a?(Array) || val.is_a?(Hash) %>

      <li class="list-group-item list-group-item-action">
        <div class="row">
          <div class="fw-bold col-6 col-md-3">
            <%= t("avito.autoload.report.#{key}") %>:
          </div>
          <div class="col-6 col-md-9">
            <% if key == 'report_id' %>
              <%= link_to val, "/stores/#{@store.id}/avito/reports/#{val}?sections=nil",
                          data: { turbo_prefetch: false } %>
            <% elsif key == 'status' %>
              <div class="row">
                <span class="badge bg-<%= if val.match?(/warning/)
                                            'warning text-dark'
                                          elsif val.match?(/success/)
                                            'success'
                                          else
                                            'primary'
                                          end %>">
                  <%= t("avito.autoload.report.#{val}") %>
                </span>
              </div>
            <% elsif key == 'started_at' %>
              <%= format_date val %>
            <% else %>
              <%= val %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>

    <div class="list-group-item list-group-item-action">
      <div class="row">
        <div class="fw-bold col-6 col-md-3">Обработано объявлений</div>
        <div class="col-6 col-md-9"><%= @report['section_stats']['sections'].map { |i| i['count'] }.sum %></div>
      </div>
    </div>

    <div class="list-group-item list-group-item-action">
      <% deleted = @report['section_stats']['sections'].find { |i| i['slug'] == 'removed_from_file' }.try(:[], 'count') || 0 %>
      <div class="row">
        <div class="ps-3 ps-md-3 fw-bold col-6 col-md-3">Объявлений в файле</div>
        <div class="col-6 col-md-9"><%= @report['section_stats']['count'] - deleted %></div>
      </div>
    </div>
  </ul>
</div>